### ISSUE TITLE
File and directory items: Add selected state; improve hover state

### ISSUE THREAD

**Issue by garrett** [KKoukiou/cockpit-navigator#56]
Here's some example SCSS which adds in a selected state (based on a `selected` class; which needs to be added could be called something else) and retools the hover state to be similar to the selected state, using CSS custom properties ("variables"). To not interrupt flow, it uses not just background, but a box shadow and an outline (with an offset) to make the selected look expand outside of its bounding box a bit.

```scss
.file-item,
.directory-item {
    &.selected,
    &:hover {
        background: var(--item-background, transparent);
        border-radius: 1px;
        box-shadow: 0 0 0 10px var(--item-background, transparent);
        outline-offset: 10px;
        outline: 1px solid var(--item-outline, transparent);
    }

    &.selected {
        --item-background: var(--pf-global--palette--blue-50);
        --item-outline: var(--pf-global--palette--blue-50);
    }

    &:hover {
        --item-background: var(--pf-global--BackgroundColor--200);
        --item-outline: var(--pf-global--BackgroundColor--200);
    }
}
```

Mockups on what it should approximately look like (these are not pixel or color perfect; the code above should be similar, but not exactly like this):

Selected:

![Navigator, selected](https://github.com/KKoukiou/cockpit-navigator/assets/10246/5ebe1c90-9bda-49b1-943f-386d7cff84a4)

Hover:

![Navigator, hover](https://github.com/KKoukiou/cockpit-navigator/assets/10246/ac4633d3-dc5a-4bc9-b584-a1057ec04085)
